### ISSUE TITLE
Other simulators that can simulate GPU-GPU communications

### ISSUE THREAD

**Issue by Liujiaqi-jlu** [sarchlab/mgpusim#106]
I would like to ask if you know of any other simulators, besides your mgpu simulator, that can be used for simulating communication between multiple GPUs. I would like to conduct a comparative study.

**Comment by syifan** [comment]
Other simulators like GPGPUSim can simulate GPU-GPU communication. They are usually completed by configuring a slow network between a cluster of cores/caches. To my best knowledge, MGPUSim is the only simulator that supports true multi-GPU systems, where GPUs can run different kernels.

**Comment by Liujiaqi-jlu** [comment]
> Other simulators like GPGPUSim can simulate GPU-GPU communication. They are usually completed by configuring a slow network between a cluster of cores/caches. To my best knowledge, MGPUSim is the only simulator that supports true multi-GPU systems, where GPUs can run different kernels.

Thank you! I've also looked into GPGPU-Sim, but I noticed it primarily simulates on-chip networks and doesn’t mention multi-GPU interconnection. Your paper also mentions that GPGPU-Sim cannot simulate interconnection, which is why I had this question.

**Comment by syifan** [comment]
It is not very important to "simulate multi-GPU interconnection." You can always config on-chip network links to model inter-GPU connections' bandwidth and latency.
