### ISSUE TITLE
Integrating Ramulator2 in MGPU-SIM

### ISSUE THREAD

**Issue by karmakar-manish** [sarchlab/mgpusim#116]
We were trying to integrate Ramulator2 in MGPU-SIM. We are unable to locate the  LLC miss (a request which is going to DRAM). Could you please help us to understand the flow or give the path to the file from which we will get the information regarding DRAM access.

**Comment by syifan** [comment]
If the Akita's DRAM model is used, here is where we receive transactions. https://github.com/sarchlab/akita/blob/v3/mem/dram/memcontroller.go#L74. 

If the ideal memory controller is used, here is the place. 
https://github.com/sarchlab/akita/blob/v3/mem/idealmemcontroller/comp.go#L84

Could you let us know how you integrate Ramulator2. Do you export traces from MGPUSim and feed into Ramulator 2?

**Comment by LailaChitra** [comment]
Hi,
Thanks for the info. Yes, we will collect the traces from MGPUSim and feed them into Ramulator2.

**Comment by syifan** [comment]
Sure. Thank you for letting us know. Please let us know if you have more questions. We will close this issue, but please feel free to reopen if needed.
