### ISSUE TITLE
Multi GPU execution results in all GPUs having 0 kernel time except the last one

### ISSUE THREAD

**Issue by Navknight** [sarchlab/mgpusim#117]
**To Reproduce**
MGPUSim version of commit ID: 
v3, Latest
Command that recreates the problem
```bash
Command  ./pagerank -node=8192 -iterations=0.5 -sparsity=0.5 -gpus=1,2 -report-all -timing
```

**Current behavior**
The GPU kernel time comes out to be 0 for GPUs  1
and only GPU 2 shows a kernel time. Same for all the other metrics.

**Expected behavior**
All GPUs should have some kernel time

**Screenshots**
![image](https://github.com/user-attachments/assets/b8a651ff-d06a-4e9f-8073-297f08365b10)

**Comment by syifan** [comment]
I can recreate this problem. I will look into it. Does it only happen to PageRank?

**Comment by syifan** [comment]
So, the problem is that PageRank benchmark does not support "true multi-GPU" execution. This is because the benchmark is not modified to utilize multiple GPUs. If you want to run multi-GPU mode for this benchmark, please use `-unified-gpus=1,2` instead of `-gpus`. Unified GPUs merge the GPUs under a single GPU interface so that the benchmark only sees one GPU.

**Comment by Navknight** [comment]
Thanks for responding to the question! is there a list somewhere which can tell me what benchmarks support multiple GPUs? Also, from the youtube videos I gathered that the `-unified-gpus` flag divides the data among the GPUs in a stride and the `-gpus` flag does it such that when a GPU first requests for it, the data is given to it and then the data stays in that GPU. 
The paper for MGPUsim mentions about PASI, how does that tie into these modes?

**Comment by syifan** [comment]
This is a very complex question to answer. 

We do not have a list of benchmarks that support `-gpus` mode. In general, only a few simple benchmarks support it. Most benchmarks do not. A key to tell is the `Distribute` function. If the benchmark calls `Distribute`, it supports `-gpus` mode. 

The `-unified-gpus` command distributes the pages in an interleaving way (one page per GPU). In `-gpu` mode, the pages are distributed into segments. Say if I have 100 pages and 4 GPUs, the first 25 page goes to GPU1. 

PASI is not supported in the current version of MGPUSim.
