### ISSUE TITLE
Why only RDMA is used for GPU-to-GPU communication?

### ISSUE THREAD

**Issue by zL1nX** [sarchlab/mgpusim#121]
Hello! It seems that only the RDMA technique is implemented for peer-to-peer (P2P) communication of GPUs, but I notice that there are well-presented PCIe functions to build the basic interconnect infrastructure. The PCIe P2P function is also [supported](https://github.com/sarchlab/akita/blob/v3/noc/acceptance/pcie_p2p/main.go) in Akita.

So why PCIe P2P is not used here for local P2P communications? In my understanding, RDMA is more often used in *remote* scenarios, e.g., cross-node transmission, with the involvement of NIC or other network-related fabrics. In the context of MGPUSim, it is more like the single node setting since there is only one driver managing multiple GPUs. 

Particularly, the RDMA functions here are used for data transmission in (local) page migration. I'd like to know why PCIe P2P is not used for this part. Thanks in advance!

**Comment by DX990307** [comment]
Good question, the RDMA is a component of the GPU, and the PCIe or the NVLink is much more related to the bus. All of them are used in P2P communication, the RDMA takes charge of sending/receiving data to/from the PCIe bus.

**Comment by zL1nX** [comment]
Thank you! So does this mean that the RDMA engine here takes on some functions of the PCIe controller on a GPU? In this way, a unified interconnect interface can be created through RDMA regardless of in local or remote scenarios. Are there other reasons behind this design choice? Forgive me if my guess is wrong.

**Comment by DX990307** [comment]
In my opinion, the answer is no. RDMA takes charge of receiving messages or preparing to send messages from the GPU phase. The PCIe takes charge of fetching messages from RDMA, routing, and sending messages to the proper destination.

**Comment by zL1nX** [comment]
I understand a bit now. Therefore, the PCIe functions are actually "silently" called under the RDMA layer. 

But I still don't quite understand what "remote" means in RDMA here? In other words, what is the difference between a RMDA engine here (with PCIe backed) and a DMA engine? Can RDMA engines bypass the PCIe infrastructure for direct p2p communication in MGPUSim? I have read the MGPUSim paper and re-searced source code, but couldn't find any indication. Please correct me if I miss something. Thanks!

**Comment by syifan** [comment]
You can consider PCIe in MGPUSim only a network model for latency and bandwidth. We do not really implement protocols, including P2P, in PCIe. I agree that the name of RDMA is a bit misleading here. But you can consider it as a network interface between GPUs. RDMA can work with different underlying networks (e.g., PCIe, NVLink, Ethernet). In RDMA, the remote means another GPU. DMA engine is responsible for memory copy (like cudaMemcpy calls). But RDMA is responsible for read/write an address that belongs to another GPU that is directly issued from a load/store instructions during kernel execution.

**Comment by zL1nX** [comment]
Thanks very much! Your explanantion is useful. This issue has been clarified to me.
