### ISSUE TITLE
MultiNode Simulation

### ISSUE THREAD

**Issue by amelfatima1231** [sarchlab/mgpusim#6]
Is it possible to simulate multiple interconnected nodes? What changes (a high level description) will be required if we want to simulate multiple interconnected nodes where each node consists of a CPU and multiple GPUs?

**Comment by syifan** [comment]
Yes. You can configure the multiple nodes by adding network links that are slower than intra-node links. 

The only problem is that we do not support multiple CPUs in a system. I guess you do not care too much about CPUs? You can always create a magic link that connect the CPU to the GPU switches. See my hand drawing below.

![IMG_0500A8E1A0E4-1](https://github.com/sarchlab/mgpusim/assets/2524066/7e7fbc63-74be-49a9-a287-468eae0386b3)

You can configure the network the anyway you want. Currently, the default configuration uses the PCIe connector to establish the network. https://github.com/sarchlab/akita/blob/v3/noc/networking/pcie/pcie.go#L14. To define your own network, my recommendation is to create a new network connector (or modify the PCIe connector).

**Comment by amelfatima1231** [comment]
Just to confirm, will we have a single root complex in this case or two?

**Comment by syifan** [comment]
> Just to confirm, will we have a single root complex in this case or two?

Single root complex. The address spaces are unified. Works as if they are in a single machine, but just a link being slower.

**Comment by amelfatima1231** [comment]
Thanks. 
Also, can't we directly connect the two SWs instead of creating an additional SW (labelled as NIC) between them? I can create another function which connects the two SWs together with different bandwidth and latency parameters?

**Comment by syifan** [comment]
> Thanks. Also, can't we directly connect the two SWs instead of creating an additional SW (labelled as NIC) between them? I can create another function which connects the two SWs together with different bandwidth and latency parameters?

Yes. That should work. Just make sure not to create a path that the traffic can bypass the slow link. The current routing algorithm is maximum-bandwidth-based routing.

**Comment by amelfatima1231** [comment]
Got it. 

Thank you so much.

**Comment by amelfatima1231** [comment]
Queries resolved.

**Comment by amelfatima1231** [comment]
Since the root complex also works as a switch, I see that the path from the switch across the root complex and into the other switch is followed instead of the direct connection between them. :/

**Comment by syifan** [comment]
> Since the root complex also works as a switch, I see that the path from the switch across the root complex and into the other switch is followed instead of the direct connection between them. :/

Is the CPU-GPU communication important for you case. If not, simply add the CPU to a single machine should solves the problem. Otherwise, you have to modify the routing algorithm.

**Comment by amelfatima1231** [comment]
No, the CPU-GPU communication is not important in this case.

**Comment by amelfatima1231** [comment]
Got it. I will try this now.

**Comment by syifan** [comment]
If CPU-GPU communication is not important to you, do not forget to use `magic-memory-copy` option. It will save some simulation time.
