### ISSUE TITLE
total_kernel_time = 0 when using unified-gpus

### ISSUE THREAD

**Issue by InnoBogus** [sarchlab/mgpusim#78]
**To Reproduce**
MGPUSim version of commit ID: 

Command that recreates the problem
```bash
Command
```

**Current behavior**
A clear and concise description of what is wrong.

**Expected behavior**

**Screenshots**
![图片](https://github.com/sarchlab/mgpusim/assets/62384242/1acb0c17-5bbd-48a3-b2e0-d4fbfd572dde)

**Additional context**
wondering if it's a bug or something wrong about my instruction

**Comment by DX990307** [comment]
Hi, I fixed this bug, and it works now. You can try it again by using the code in the new branch.
